### PR TITLE
Adding nwt_pikas

### PR DESCRIPTION
**Pull request by adhil0**
- Added data, documentation, and modified vignette for `nwt_pikas`
- Added `sf`, `ggmap`, and `leaflet` to `SUGGESTS`

Let me know if any improvements can be made!

### CODE REVIEW

**Comment by brunj7** [comment]
Hi @adhil0 ,

Thank you for all the work on this, it looks really great!!

@allisonhorst and I talked about the vignette today and had a few suggestions / comments:

- you do not need `mutate` to perform projection transformation on an `sf` data frame, you can directly apply the function (`st_set_crs(pikas_sf, 26913)`)
- We think the examples of the maps package do not add too much information and suggest to drop it and jump to the `ggmap` terrain maps, after the first plot
- Add a tooltip to the leaflet map using the concentration variable
- Add more code comments on the data cleaning script :)

Let us know if you have any questions or thoughts on these suggestions

**Comment by adhil0** [comment]
>     * you do not need `mutate` to perform projection transformation on an `sf` data frame, you can directly apply the function (`st_set_crs(pikas_sf, 26913)`)
> 
>     * We think the examples of the maps package do not add too much information and suggest to drop it and jump to the `ggmap` terrain maps, after the first plot
> 
>     * Add a tooltip to the leaflet map using the concentration variable
> 
>     * Add more code comments on the data cleaning script :)

I added these suggestions!

**Comment by brunj7** [comment]
Thank you for iterating on this @adhil0!! it looks great, merging now

**Comment by adhil0** [comment]
@brunj7 Awesome, let me know if there's anything else I can help with

**Pull request merged**
